site_name: MPU-6500/9250 TI-RTOS Driver
site_description: A comprehensive C/C++ driver for the MPU-6500 and MPU-9250 on the TI-RTOS platform.
docs_dir: doc
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Home': 'index.md'
  - 'API Reference':
    - 'Base C Library': 'api/c_driver.md'
    - 'C++ DMP Class': 'api/cpp_class.md'

plugins:
  - search
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences