site_name: MPU-9250 TI-RTOS Driver
site_description: A comprehensive C/C++ driver for the MPU-9250 on the TI-RTOS platform.

docs_dir: doc

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 'Home': 'index.md'
  - 'API Reference':
    - 'Base C Library': 'api/c_library.md'
    - 'C++ DMP Class': 'api/cpp_class.md'
    - 'C-Compatible Wrapper': 'api/c_wrapper.md'
